"Plugins

" Initialize plugin system
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'dhruvasagar/vim-table-mode'

call plug#end()

" Visual Configs
syntax on
set number
set showtabline=2

" Typeset configs
set tabstop=2

" Search configs 
set ignorecase
set hlsearch

" Spelling Configuration
hi clear SpellBad
hi SpellBad cterm=underline ctermfg=red

" Mouse Settings
set mouse=a

" Keymappings
noremap -- :NERDTree <CR>
noremap ++ :TableModeToggle <CR>
